language: cpp

addons:
  apt:
    packages:
      - cmake
      - make
      - gcc
      - g++
      - flex
      - bison
      - python
      - libpcap-dev
      - libssl-dev
      - zlib1g-dev
      - libkrb5-dev
      - git
      - sqlite3
      - curl
      - bsdmainutils

stages:
  - setup
  - test

jobs:
  include:
    - stage: setup
      script:
        - git clone --recursive https://github.com/bro/bro.git ../bro-src
        - pushd ../bro-src && ./configure --prefix=../bro && make && make install && popd
        - pip install bro-pkg
        - PATH="../bro/bin:$PATH" bro-pkg autoconfig

    - stage: test
      script:
        - bro-pkg test .
