language: cpp

addons:
  apt:
    packages:
      - cmake
      - make
      - gcc
      - g++
      - flex
      - bison
      - python
      - libpcap-dev
      - libssl-dev
      - zlib1g-dev
      - libkrb5-dev
      - git
      - sqlite3
      - curl
      - bsdmainutils

stages:
  - setup
  - test

jobs:
  include:
    - stage: setup
      script:
        - git clone --recursive https://github.com/bro/bro.git "$HOME"/bro-src
        - pushd "$HOME"/bro-src && ./configure --prefix="$HOME"/bro && make && make install && popd
        - pip --user install bro-pkg
        - PATH="$HOME/.local/bin:$HOME/bro/bin:$PATH" bro-pkg autoconfig

    - stage: test
      script:
        - PATH="$HOME/.local/bin:$HOME/bro/bin:$PATH"bro-pkg test .
